// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaLY0H1ZcUigddp7tQZOekJ2232ncLlQQ',
    appId: '1:308772479666:web:1caa7fd16449173da31fab',
    messagingSenderId: '308772479666',
    projectId: 'el-sharq-clinic-system',
    authDomain: 'el-sharq-clinic-system.firebaseapp.com',
    storageBucket: 'el-sharq-clinic-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyByX3as8r03wkpzxx4YIXOk8G9HW0QbM',
    appId: '1:308772479666:android:71559f225546d209a31fab',
    messagingSenderId: '308772479666',
    projectId: 'el-sharq-clinic-system',
    storageBucket: 'el-sharq-clinic-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA2Rtsg1ftRalQICvKYjx3cMMmNoKQ52Y',
    appId: '1:308772479666:ios:3ed929d3b6d6bb49a31fab',
    messagingSenderId: '308772479666',
    projectId: 'el-sharq-clinic-system',
    storageBucket: 'el-sharq-clinic-system.appspot.com',
    iosBundleId: 'com.example.elSharqClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaLY0H1ZcUigddp7tQZOekJ2232ncLlQQ',
    appId: '1:308772479666:web:44939be9741aee30a31fab',
    messagingSenderId: '308772479666',
    projectId: 'el-sharq-clinic-system',
    authDomain: 'el-sharq-clinic-system.firebaseapp.com',
    storageBucket: 'el-sharq-clinic-system.appspot.com',
  );
}
